### ISSUE TITLE
Data 21 Suppléments

### ISSUE THREAD

**Issue by the-prism** [strudelauxpommes/FitnessHabits#25]
Description:

Implémentation des données enregistrés pour le modèle

Acceptance Criteria:

- Création de nouvelles entrées dans la table
- Enregistrements des modifications
- Informations disponibles pour la vue (Implémentation externe)

ref: #14 #21

**Comment by Hentouane** [comment]
![supplements-specs](https://user-images.githubusercontent.com/12865898/33232148-e7175432-d1ce-11e7-8923-431c7442586c.jpg)

**Comment by jeansalama** [comment]
Fermeture de cet "issue" pour archivage
