### ISSUE TITLE
Data 8 Breuvages

### ISSUE THREAD

**Issue by CaptainVolcom** [strudelauxpommes/FitnessHabits#26]
Description:

Implémentation des données enregistrés pour le modèle

Acceptance Criteria:

- Création de nouvelles entrées dans la table
- Enregistrements des modifications
- Informations disponibles pour la vue (Implémentation externe)

ref #14, #9, #18

**Comment by Aduleten** [comment]
Bonjour, Après avoir parlé à Fabrice tantôt en classe, il semblait demander suggestion sur le genre d'info que nous aurions besoin pour nos breuvages. J'ai fait la liste suivante, qui pourrait changer et évoluer avec le temps : 

GET:
  getBreuvageInfos(date)
	Devrait renvoyer une liste de tout les breuvages et leur quantité en ml consommé pour cette date. (le reste du visuel, total, etc. est géré par nous).

POST:
  addMLtoBreuvage(idBreuvage, mlToAdd, date)
	pour couvrir le - et le + des détails et le onClick d'une rangée sur le sommaire (c'est a nous de passer des bon params. de qté ajouté à ce moment la.) Si on clique sur le - on ajoute une quanité négative évidemment.

  replaceMLtoBreuvage(idBreuvage, mlToReplace, date)
	quand on modifie directement la qté consommé pour un breuvage dans la page détail.

  addCommentBreuvage(comment, date)
	quand on ajoute un commentaire pour un breuvage, peut etre utilisé aussi pour le modifier si on overwrite.


À noter, Beaucoup plus simple de toujours passer la date pour pouvoir mieux gérer la modification des journées antérieurs à cause du swipe left/right

**Comment by jeansalama** [comment]
Fermeture de cet "issue" pour archivage
