### ISSUE TITLE
Data 8 Exportation

### ISSUE THREAD

**Issue by the-prism** [strudelauxpommes/FitnessHabits#27]
Description:

En tant qu'utilisateur je veut pouvoir exporter mes données saisies afin de les consulter sur un autre appareil.

Acceptance Criteria:

- Toutes les données sont exportées dans un seul fichier
- Les paramètres de l’application sont aussi exportés
- Les données sont identiques à ceux dans la base de données

ref: #14 #15

**Comment by jeansalama** [comment]
Fermeture de cet "issue" pour archivage
