### ISSUE TITLE
Data 8 Alcool

### ISSUE THREAD

**Issue by CaptainVolcom** [strudelauxpommes/FitnessHabits#30]
Description:

Implémentation des données enregistrés pour le modèle

Acceptance Criteria:

- Création de nouvelles entrées dans la table
- Enregistrements des modifications
- Informations disponibles pour la vue (Implémentation externe)

ref #14, #10, #11

**Comment by wetwicky** [comment]
voir le wiki pour plus d'information:
https://github.com/strudelauxpommes/FitnessHabits/wiki/Besoins-Malbolge-pour-les-données

**Comment by jeansalama** [comment]
Fermeture de cet "issue" pour archivage
