### ISSUE TITLE
Data 13 Nourriture

### ISSUE THREAD

**Issue by the-prism** [strudelauxpommes/FitnessHabits#31]
Description:

Implémentation des données enregistrés pour le modèle

Acceptance Criteria:

- Création de nouvelles entrées dans la table
- Enregistrements des modifications
- Informations disponibles pour la vue (Implémentation externe)

ref: #14 #12 #13

**Comment by levgui** [comment]
# Information à stocker pour l'équipe nourriture:

## Liste des repas d'une journée
La liste des repas d'une journée (Déjeuner, Diner, Collation, Souper, etc..) sera gérée dans les paramètres, mais nous devrons quand même identifier nos entrées de portions et de commentaire avec le repas auquel elles correspondent.

## Les catégories d'aliments 
* idCategorie
* nomCategorie 
* pictogramme (path de l'image correspondant à la catégorie)
* favoris (oui ou non, 1 ou 0, true ou false)

Par défaut, cette liste contient "Protéines", "Fruits", "Légumes", "Glucides", "Gras", puis d'autres pourront être ajoutées ou modifiées. Peut-être à discuter si l'id est nécessaire ou si on identifie une catégorie seulement avec son nom.

## Entrées de portions
* date
* repas (nom du repas?)
* idCategorie ou nomCategorie (à discuter)
* nbPortions

1. Nous devons pouvoir ajouter un enregistrement. Si un enregistrement existe déjà pour la combinaison de la date, le repas et la catégorie, il faut l'update à la place (à voir?). 
Par exemple : 5 portions de glucides au diner le 25 novembre 2017.

1. Nous devons pouvoir demander le nombre de portions selon une date, un repas et une catégorie. 
Par exemple, combien de portions de glucides le 25 novembre 2017 au diner ? Réponse : 5.

1. (souhaitable) Pouvoir recevoir la liste des portions de toutes les catégories selon une date et un repas. 
Par exemple: Liste des portions le 25 novembre 2017 au diner ? Réponse: [glucides: 2, fruits:1, legumes:1] (catégories absentes = 0 portions). 
Ça nous éviterait de devoir faire une requête différente pour chaque catégorie d'aliment à chaque fois qu'on change de repas.

1. (souhaitable) Pouvoir recevoir le total des portions de chaque catégorie pour tous les repas d'une journée spécifique. 
Par exemple : Total des portions le 25 novembre 2017 ? Réponse: [glucide: 7, fruits: 3, legumes: 5, gras: 8, proteines: 12]
Ça vous éviterait de faire des requêtes individuelles pour chaque repas et chaque catégorie pour en faire la somme.

## Commentaires
* date
* repas (nom du repas?)
* commentaire

Pour la section nourriture, on peut spécifier un commentaire par repas à tous les jours.

1. Nous devons pouvoir ajouter un commentaire pour une journée et un repas spécifique. S'il y a déjà un commentaire pour cette journée et ce repas, on l'update à la place.
Par exemple : 25 novembre 2017, au dîner : "Sandwich au poulet et concombres"

1. Nous devons pouvoir demander le commentaire pour une date et un repas.
Par exemple: Commentaire le 25 novembre au diner ? Réponse : "Sandwich au poulet et concombres"

1. (souhaitable) Pouvoir recevoir une chaîne concaténée de tous les commentaires pour une journée (avec un charactere newLine entre chaque commentaire)
Par exemple : Commentaires le 25 novembre ? Réponse : "Gruau \n Barre tendre \n Sandwich au poulet \n Spaghetti \n Pomme"
Ça nous éviterait de devoir faire une requête pour chaque repas de la journée pour concaténer la chaîne nous même.

N'hésitez pas à communiquer avec nous s'il y a quoi que ce soit.

**Comment by jeansalama** [comment]
Fermeture de cet "issue" pour archivage
