### ISSUE TITLE
Data 13 Activités

### ISSUE THREAD

**Issue by CaptainVolcom** [strudelauxpommes/FitnessHabits#32]
Description:

Implémentation des données enregistrés pour le modèle

Acceptance Criteria:

- Création de nouvelles entrées dans la table
- Enregistrements des modifications
- Informations disponibles pour la vue (Implémentation externe)

ref: #14, #6, #7

**Comment by jeanpierrethach** [comment]
## Activité:

id
nomActivite
duree
intensite
estFavori

## Commentaire:

date
commentaire

## Cas d'utilisation:

Lecture - Section sommaire
* Les activités favoris (nom, durée, intensité) en ordre alphabétique
* Le total d'effort de la journée
* Le total d'effort des 7 derniers jours (no.7 étant la journée courante)

Écriture - Section sommaire
* Incrémenter la durée de l'activité
* Modifier l'intensité d'une activité

Lecture - Section détaillée
* Toutes les activités (nom, durée, intensité) en ordre alphabétique
* Le total d'effort des 7 derniers jours (no.7 étant la journée courante)

Écriture - Section détaillée
* Modifier le nom d'une activité
* Modifier la durée de l'activité
* Modifier l'intensité d'une activité
* Ajouter un commentaire

**Comment by jeansalama** [comment]
Fermeture de cet "issue" pour archivage
