### ISSUE TITLE
To do list Main Page

### ISSUE THREAD

**Issue by PhilLeblanc** [strudelauxpommes/FitnessHabits#82]
**To do**
- [x] Intégration du module de langue
- [ ] Intégration du module Activités
- [x] Intégration du module Sommeil
- [x] Intégration du module Alcool (Manque les datas)
- [x] Intégration du module Nourriture
- [x] Intégration du module Breuvage
- [x] Intégration du module Import/Export
- [x] Intégration du module Suppléments
- [x] Intégration du module Poids
- [x] Intégration des Tabs
- [x] paramétrer la langue 

**Test**
- [ ] Routing pour Activités
- [x] Routing pour Sommeil
- [x] Routing pour Alcool
- [x] Routing pour Nourriture
- [x] Routing pour Breuvage
- [x] Routing pour Import/Export
- [x] Routing pour Settings
- [x] Routing pour Suppléments
- [x] Routing pour Poids
- [x] Routing pour Tabs

**Comment by PhilLeblanc** [comment]
Message à nourriture:

-Routing à refaire (nav back home)
-Template

**Comment by strudelauxpommes** [comment]
Terminé.
